name: flutter_mystery_app
description: A minimal mystery game app that loads universe.json.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  mystery: any
flutter:
  uses-material-design: true
  assets:
    - assets/universe.json